In [1]:
text = ['I am a failure','this is a line','completely different line']

In [15]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [17]:
cv = CountVectorizer()

In [18]:
sparse_matrix = cv.fit_transform(text)

In [19]:
sparse_matrix.todense()

matrix([[1, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 0, 1, 0]])

In [20]:
cv.vocabulary_

{'am': 0,
 'failure': 3,
 'this': 6,
 'is': 4,
 'line': 5,
 'completely': 1,
 'different': 2}

In [21]:
tfidf = TfidfTransformer()

In [23]:
results = tfidf.fit_transform(sparse_matrix)

In [24]:
results.todense()


matrix([[0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.62276601,
         0.4736296 , 0.62276601],
        [0.        , 0.62276601, 0.62276601, 0.        , 0.        ,
         0.4736296 , 0.        ]])

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tv = TfidfVectorizer()

In [27]:
tv_res = tv.fit_transform(text)

In [28]:
tv_res

<3x7 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [30]:
tv_res.todense()

matrix([[0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.62276601,
         0.4736296 , 0.62276601],
        [0.        , 0.62276601, 0.62276601, 0.        , 0.        ,
         0.4736296 , 0.        ]])